// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nesmcqpswtrcxlljawgo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5lc21jcXBzd3RyY3hsbGphd2dvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIyMjQyNjIsImV4cCI6MjA2NzgwMDI2Mn0.Talr4a69ENT848mo1TMfgU2UZfBPBNCW52Jwz66Kykw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});